name: Telegram Notification on Commit

on:
  push:
    branches:
      - '**' #ç›£è½æ‰€æœ‰åˆ†æ”¯çš„pushäº‹ä»¶

jobs:
  send_message:
    runs-on:ubuntu-latest

    steps:
      - name: Send Commit Notification to Telegram
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            ğŸ“¢ **GitHub Actions é€šçŸ¥**
            
            ---
            
            ğŸ› ï¸ **å°ˆæ¡ˆ**: `${{ github.repository }}`
            
            ğŸ‘¤ **æäº¤è€…**: `${{ github.actor }}`
            
            ğŸŒ¿ **åˆ†æ”¯**: `${{ github.ref_name }}`
            
            ğŸ’¬ **è¨Šæ¯**: 
            `${{ github.event.head_commit.message }}`
            
            ğŸ”— **è©³ç´°è³‡è¨Š**: [æŸ¥çœ‹ Commit](${{ github.event.head_commit.url }})
        parse_mode: markdown
